#!/bin/bash
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>  // for EXIT_FAILURE

int main() {
    char cwd[1024];

    // Get the absolute path of the current working directory
    if (getcwd(cwd, sizeof(cwd)) != NULL) {
        printf("Absolute path of the current working directory:\n%s\n", cwd);
    } else {
        perror("getcwd() error");
        return EXIT_FAILURE;
    }

    return 0;
}
